alias: Kaden Home alert
trigger:
  platform: zone
  entity_id: device_tracker.kaden_iphone
  zone: zone.home
  event: enter
action:
  service: notify.pushovernotification
  data:
    message: "Kaden has arrived home"
