alias: Jason Home alert
trigger:
  platform: state
  entity_id: device_tracker.jason_galaxy
  state: 'home'
action:
  service: notify.pushovernotification
  data:
    message: "Jason has arrived home"
