alias: Jill Home alert
trigger:
  platform: zone
  entity_id: device_tracker.jill_iphone
  zone: zone.home
  event: enter
action:
  service: notify.pushovernotification
  data:
    message: "Jill has arrived home"
