alias: Ally Home alert
initial_state: False
trigger:
  platform: state
  entity_id: device_tracker.ally_iphone
  state: 'home'
action:
  service: notify.pushovernotification
  data:
    message: "Ally has arrived home"
