alias: Jason Home alert
trigger:
  platform: zone
  entity_id: device_tracker.jason_galaxy
  zone: zone.home
  event: enter
action:
  service: notify.pushovernotification
  data:
    message: "Jason has arrived home"
