alias: Ally Home alert
trigger:
  platform: zone
  entity_id: device_tracker.ally_iphone
  zone: zone.home
  event: enter
action:
  service: notify.pushovernotification
  data:
    message: "Ally has arrived home"
