alias: Basement Motion
trigger:
  platform: state
  entity_id: binary_sensor.ecolink_unknown_type_0004_id_0001_sensor_2
  to: 'on'
action:
  service: homeassistant.turn_on
  entity_id: switch.wemo_mini_280
