alias: Basement Motion Off
trigger:
  platform: state
  entity_id: binary_sensor.ecolink_pir_motion_sensor_sensor_3_0
  state: 'off'
action:
  service: switch.turn_off
  entity_id: switch.leviton_dzpa11lw_plugin_appliance_module_switch_2_0

