alias: Hass Startup
trigger:
  platform: homeassistant
  event: start
action:
  - service: ifttt.trigger
    data: {"event":"notify_x1", "value1":"Home Assistant has Started"}
  - service: frontend.set_theme
    data: {"name":"night"}
