alias: Storm Detection
trigger:
  platform: numeric_state
  entity_id: sensor.dark_sky_nearest_storm_distance
  below: 10
action:
  - service: ifttt.trigger
    data: {"event":"notify_x1", "value1":"Storm within 10 miles"}
  - service: notify.pushovernotification
    data:
      message: "Storm within 10 miles"
