alias: Water Alert
trigger:
  platform: state
  entity_id: binary_sensor.aeotec_dsb45_water_sensor_2_sensor
  to: 'on'
action:
  - service: notify.pushovernotification
    data:
      message: "Water Detected"
  - service: ifttt.trigger
    data: {"event":"notify_x1", "value1":"Water Detected in on sensor"}
